VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 5601, host: 5601,  protocol: "tcp", auto_correct: "true"
  config.vm.network "forwarded_port", guest: 9200, host: 9200,  protocol: "tcp", auto_correct: "true"
  config.vm.network "private_network", ip: "99.99.99.102"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = 'Kibana'
    virtualbox.memory = 1024
    virtualbox.cpus = 1
    end
end
